language: node_js #设置语言
node_js: stable #设置相应版本

#缓存依赖
cache:
    apt: true
    directories:
        - node_modules #缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' #更改时区
    - npm install hexo-cli -g  #安装hexo环境
    - git clone $GH_REP_URL_SOURCE
    - cd 1630425.github.io-s
    - npm i hexo-generator-json-content --save && npm i --save hexo-wordcount && git clone https://github.com/fi3ework/hexo-theme-archer.git themes/archer --depth=1

#依赖安装
install:
    - npm install #安装hexo及插件
    - npm rebuild node-sass --force #该命令是根据构建失败的日志提示添加的

#构建脚本
script:
    - hexo clean #清除
    - hexo g #生成

after_script:
  - git clone https://$GH_REP_URL_PAGES .deploy_git  #GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ $CUSTOM_PATH   #这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd $CUSTOM_PATH
  - rm -f .gitignore .travis.yml desc run-desc.md
  - git config user.name $GIT_NAME  #修改name
  - git config user.email $GIT_EMAIL  #修改email
  - git add -A
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  #提交记录包含时间 跟上面更改时区配合
  #- git push --force --quiet "https://$GH_TOKEN@${GH_REF}" master:master #GH_TOKEN是在Travis中配置环境变量的名称  
  - git push --force --quiet "https://$GH_TOKEN@$GH_REP_URL_PAGES" master:master #GH_TOKEN是在Travis中配置环境变量的名称        

notifications:
  email:
    - 1630425@qq.com
  on_success: change
  on_failure: always